### ISSUE TITLE
Not enough bandwidth for any playback of this item. Cannot convert to below minimum bandwidth of 103kbps.

### ISSUE THREAD

**Issue by Cyb3rGh05t** [Cigaras/IPTV.bundle#163] opened 2017-11-03 13:17 UTC
hey :)

i like your plugin, keep up that good work.

i have sometimes a issue when trying to play a stream, i get this:

![screen shot 2017-11-03 at 14 13 59](https://user-images.githubusercontent.com/5200101/32375359-975ec3a0-c0a1-11e7-9af2-0e66c8030ae3.png)

I have a 200mb internet connection.

And sometimes when the stream plays , it goes out of sync :/

Any ideas what i could change?

thanks

**Comment by Cyb3rGh05t** [comment] 2017-11-03 13:39
I am on Plex/web, apple tv 4k and playstation 4 pro.

**Comment by Feducu** [comment] 2017-11-05 18:57
Same for me on Roku

**Comment by Cigaras** [comment] 2017-11-06 12:32
Google [says](http://lmgtfy.com/?q=Not+enough+bandwidth+for+any+playback+of+this+item.+Cannot+convert+to+below+minimum+bandwidth+of+103kbps.) it helps to change [video](https://forums.plex.tv/discussion/241553/error-playback-was-not-possible-not-enough-bandwidth-for-any-playback-of-this-item) [quality](http://forums.plex.tv/discussion/comment/1428624) [to](https://forums.plex.tv/discussion/282612/playback-error) [original](https://www.reddit.com/r/PleX/comments/60p9wg/not_enough_bandwidth_to_play/).

[![g5R5Dp8.png](http://i.imgur.com/g5R5Dp8.png)](http://forums.plex.tv/discussion/comment/1428624) [![S6tqqsT.png](https://i.imgur.com/S6tqqsT.png)](https://forums.plex.tv/discussion/282612/playback-error)

**Comment by gregf** [comment] 2017-11-06 15:45
@Cigaras I tried this, made no difference.

**Comment by Cyb3rGh05t** [comment] 2017-11-06 16:09
Same for me. It makes no difference. Do u need a log maybe?

**Comment by Cigaras** [comment] 2017-11-07 11:33
I'd prefer a stream url instead of log, because as plug-in does not play videos by it self, there will be nothing useful in its log for me, however maybe I could see something suspicious if I had a way to reproduce the issue.

**Comment by MichealCollinsNS90** [comment] 2017-12-20 01:11
This was an issue with Plex and has been almost resolved with the newest server update (1.10.1.4602) here:
[https://forums.plex.tv/discussion/62832/plex-media-server/p10](url)

> (Streaming Brain) Playback involving transcodes of some channel content failed with bandwidth error (#7911)

When I say "almost", I have tested the following devices:

**Local access:**
- Web browser ( **Native Successful**)
- Chromecast (**Transcoding Successful**)
- Xbox One (**Native Successful**)
- PS4 (**Native Successful**)
- Android App (**UNSUCCESSFUL**)
- iOS App (**UNSUCCESSFUL**)

I will be travelling in a few days and will be testing all of the above devices remotely and will let you know the outcome.

**Comment by GoNotCougsWA** [comment] 2017-12-28 18:27
It seems to be if you choose the beta version of Plex (Only for Plex Pass) install the beta version. Install the Plex Media Player. It seems to work fine. Plex is now supporting mu3u/HTTP playlists. It's right now beta for now.

**Comment by MichealX64** [comment] 2017-12-28 18:40
Yes, I have read somewhere that this update has only been release for Beta, but I have not opted for Beta releases? My PMS is only set up to download "Public" or stable releases so I do not know why I have a beta release...?

I have returned from travelling over the holidays and have tested the devices in my previous comment if anyone is interested in device compatibility.

**Remote access:**
- Web browser ( **UNSUCCESSFUL**)
- Chromecast (**Transcoding Successful**)
- Xbox One (**Native Successful**)
- PS4 (**Native Successful**)
- Android App (**UNSUCCESSFUL**)
- iOS App (**UNSUCCESSFUL**)

**Comment by GoNotCougsWA** [comment] 2018-01-21 19:12
Come to think of it. I think they release it to the public.

**Comment by skynono** [comment] 2018-04-07 16:44
I ´ve tried successfully with ps4 with direct video option disabled it.
Ios plex beta same thing working.
Web too it’s working well ...
Super thx cigaras just now i wanna know if somebody knows how to monitoring multiple users watching tv in pms or plexpy or tautully please?

**Comment by GoNotCougsWA** [comment] 2018-04-07 17:57
>From skynono.
>I ´ve tried successfully with ps4 with direct video option disabled it.
>Ios plex beta same thing working.
>Web too it’s working well ...
>Super thx cigaras just now i wanna know if somebody knows how to monitoring multiple users >watching tv in pms or plexpy or tautully please?
1) Sorry, next time when you make a comment please make use it make sense.
2) Like what do you mean by watching tv? You cannot monitor people watching stuff on a channel. Only when watching something on plex non channel.

**Comment by skynono** [comment] 2018-04-07 18:52
Hello Sir GoNotGousWa
Sorry do you speak spanish or french or portuguese maybe not ...  the world is not full of english people and i try speaking as i can. Well i can see your answer and now i know you understand everything what i have wrote. Thanks for your fake answer number 2 and if i can help people with my poor english is better than nothing no?
Faithfully (the foreigner)

**Comment by GoNotCougsWA** [comment] 2018-04-07 19:06
> From Skynono:
>Hello Sir GoNotGousWa
>Sorry do you speak spanish or french or portuguese maybe not ... the world is not full of english people >and i try speaking as i can. Well i can see your answer and now i know you understand everything what >i have wrote. Thanks for your fake answer number 2 and if i can help people with my poor english is >better than nothing no?
>Faithfully (the foreigner)

Fine, I will speak in spanish.
¿Qué quieres decir con respuesta falsa? Lo que estaba diciendo es que no creo que puedas hacer eso.

**Comment by skynono** [comment] 2018-04-07 19:12
FYI you can monitor the channel with Telly (proxy iptv emulate tuner dvr) it’s why i’m asking this.
Peace ✌🏼

**Comment by skynono** [comment] 2018-04-07 19:26
Tambien puedo hablar español even in chinese (google translate) se quieres lol ok way vamos ... take it easy. 
Find out Telly.
Peace✌🏼 C U

**Closed** 2018-09-26 11:20 UTC
Labels: Duplicate, Plex issue
