### ISSUE TITLE
Can play on plex html but not rasplex

### ISSUE THREAD

**Issue by therudy** [Cigaras/IPTV.bundle#76] opened 2017-02-10 20:28 UTC
hello, small question

i can play m3u file from plex with google chrome

but on my rasplex, i load iptv, and when i select a channel, nothing is launched

any idea ?

stream/direct play is disabled

**Comment by Cigaras** [comment] 2017-02-22 12:28
Might be same issue as #66 and some NAS players are having, I am investigating it right now but I am unable to reproduce it because I do not have devices that have this issue. Could You please share Your [log](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting) when trying to play on rasplex?

If You could test one more thing I'd be very grateful, please reduce Your playlist to 2-3 streams and test it with [IPTV v.2.0.0](https://github.com/Cigaras/IPTV.bundle/archive/beta.zip) and [IPTVLite](https://github.com/Cigaras/IPTVLite.bundle) on rasplex and share Your results here.

**Comment by dan-the-man-nz** [comment] 2017-02-24 03:09
Hi

dan-the-man from the openpht/rasplex testing team

i can confirm this issue and from others posting on the openpht forum etc,  I have tried your plugin, but not able to get it to work in openpht windows/embedded/rasplex and original plex home theatre.  (works fine in plexweb and PMP tho)

i am able to use other video channels with openpht/rasplex just fine, but not this bundle

is this something you would be willing to look at?

for example if you did find it was actually something openpht/rasplex is going wrong maybe we could get this in the next openpht/rasplex release, but as i mentioned, other video channels work fine in openpht/rasplex

the dev did have a quick look the logs i showed him of it not working but nothing jumped out as openpht/rasplex been the cause.

thanks. Daniel

**Comment by Cigaras** [comment] 2017-02-24 12:55
If it's the same problem as #66 then it should be fixed in current [beta](https://github.com/Cigaras/IPTV.bundle/tree/beta) build.

If clicking works in Rasplex but video does not play, it should give an error, I would be glad to know the error.

**Comment by dan-the-man-nz** [comment] 2017-02-24 19:08
Hi

i tried your beta, and it is working !

good work

**Closed** 2017-03-07 07:21 UTC
Labels: Fixed
